services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'development_railsgoat'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root"]
      interval: 5s
      timeout: 10s
      retries: 3

  web:
    image: insecureapps/railsgoat-web:latest
    platform: linux/amd64
    command: bash -c "rm -f tmp/pids/server.pid; bundle exec rake db:setup; sleep 5; bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: mysql
      DB_USERNAME: root
      DB_PASSWORD:
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
