# https://github.com/christophetd/log4shell-vulnerable-app
services:
  log4shell-vulnerable-app:
    name: log4shell-vulnerable-app
    image: ghcr.io/christophetd/log4shell-vulnerable-app@sha256:6f88430688108e512f7405ac3c73d47f5c370780b94182854ea2cddc6bd59929
    container_name: log4shell-vulnerable-app
    ports:
      - "8080:8080"
    restart: always
