version: "3.2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql

  javaspringvulny:
    image: insecureapps/javaspringvulny:latest
    container_name: javaspringvulny
    environment:
      SPRING_PROFILES_ACTIVE: postgresql
    ports:
      - "9000:9000"
    links:
      - db
    depends_on:
      - db
