# https://github.com/vulnerable-apps/govwa
services:
  web:
    image: insecureapps/govwa:latest
    container_name: govwa
    ports:
    - "8888:8888"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    container_name: db_mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_HOST=mysql-host
      - MYSQL_USER=govwauser
      - MYSQL_PASSWORD=govwaP@ss
      - MYSQL_DATABASE=govwa
      - MYSQL_ROOT_PASSWORD=admin321
