# https://github.com/vulnerable-apps/DVWA
volumes:
  dvwa:

services:
  dvwa:
    container_name: dvwa
    image: insecureapps/dvwa-unauth:latest
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always

  db:
    image: insecureapps/dvwa-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    restart: unless-stopped